import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Card, CardHeader, CardContent, CardTitle } from '../../components/ui/Card';
import { Button } from '../../components/ui/Button';
import { Input } from '../../components/ui/Input';
import { 
  Bot, 
  Sparkles, 
  Save,
  Loader2
} from 'lucide-react';
import { toast } from 'sonner';

const CreateRecipe = () => {
    const navigate = useNavigate();
    const [prompt, setPrompt] = useState('');
    const [isGenerating, setIsGenerating] = useState(false);
    const [generatedRecipe, setGeneratedRecipe] = useState<{
        name: string;
        description: string;
        ingredients: { name: string; amount: string }[];
        instructions: string;
    } | null>(null);

    const handleGenerate = async () => {
        if (!prompt) return;
        setIsGenerating(true);
        try {
            // Simulate AI Generation
            await new Promise(resolve => setTimeout(resolve, 3000));
            
            // Mock AI Response based on prompt
            setGeneratedRecipe({
                name: 'AI Generated: ' + prompt.split(' ').slice(0, 3).join(' ') + '...',
                description: `Optimized formulation for ${prompt}. Focused on cost-efficiency and texture stability.`,
                ingredients: [
                    { name: 'Cocoa Mass', amount: '500 kg' },
                    { name: 'Cocoa Butter', amount: '150 kg' },
                    { name: 'Sugar', amount: '350 kg' },
                    { name: 'Emulsifier (Soy Lecithin)', amount: '5 kg' }
                ],
                instructions: `1. Melt cocoa mass at 50°C.\n2. Mix in sugar and emulsifiers.\n3. Refine to 20 microns.\n4. Conche for 12 hours.\n5. Temper and mold.`
            });
            toast.success("Recipe generated by AI!");
        } catch (error) {
            toast.error("Generation failed");
        } finally {
            setIsGenerating(false);
        }
    };

    const handleSave = () => {
        toast.success("Recipe saved successfully!");
        navigate('/recipes');
    };

    return (
        <div className="max-w-4xl mx-auto space-y-8 pb-12 animate-fade-in">
            <div className="text-center space-y-4">
                <div className="bg-gold-100 p-4 rounded-full w-fit mx-auto animate-bounce-slow">
                    <Sparkles className="h-8 w-8 text-gold-600" />
                </div>
                <h1 className="text-4xl font-bold font-serif text-cocoa-900">AI Recipe Creator</h1>
                <p className="text-xl text-slate-600 max-w-2xl mx-auto">
                    Describe your desired product (e.g., "Vegan Milk Chocolate with hazelnut undertones"), and our AI will formulate the perfect recipe.
                </p>
            </div>

            <Card className="border-gold-200 shadow-lg border-2">
                <CardContent className="pt-6">
                    <div className="flex gap-4">
                        <Input 
                            placeholder="Describe your recipe idea..." 
                            className="h-14 text-lg border-gold-200 focus:border-gold-500 bg-gold-50/30"
                            value={prompt}
                            onChange={(e) => setPrompt(e.target.value)}
                            onKeyDown={(e) => e.key === 'Enter' && handleGenerate()}
                        />
                        <Button 
                            className="h-14 px-8 bg-gold-600 hover:bg-gold-700 text-white text-lg font-bold shadow-md hover:shadow-lg transition-all"
                            onClick={handleGenerate}
                            disabled={isGenerating || !prompt}
                        >
                            {isGenerating ? (
                                <>
                                    <Loader2 className="h-6 w-6 animate-spin mr-2" />
                                    Creating...
                                </>
                            ) : (
                                <>
                                    <Bot className="h-6 w-6 mr-2" />
                                    Generate
                                </>
                            )}
                        </Button>
                    </div>
                </CardContent>
            </Card>

            {generatedRecipe && (
                <div className="space-y-6 animate-in slide-in-from-bottom-10 fade-in duration-700">
                    <div className="flex justify-between items-center px-4">
                        <h2 className="text-2xl font-bold text-cocoa-900 border-l-4 border-gold-500 pl-4">
                            Generated Formulation
                        </h2>
                        <Button onClick={handleSave} className="bg-green-600 hover:bg-green-700 text-white gap-2">
                            <Save className="h-4 w-4" /> Save to Recipe Book
                        </Button>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        <Card className="border-cocoa-100">
                            <CardHeader>
                                <CardTitle className="text-lg text-cocoa-800">Ingredients</CardTitle>
                            </CardHeader>
                            <CardContent>
                                <ul className="space-y-3">
                                    {generatedRecipe.ingredients.map((ing, i) => (
                                        <li key={i} className="flex justify-between items-center p-2 bg-slate-50 rounded border border-slate-100">
                                            <span className="font-medium text-slate-700">{ing.name}</span>
                                            <span className="font-mono text-slate-500">{ing.amount}</span>
                                        </li>
                                    ))}
                                </ul>
                            </CardContent>
                        </Card>

                        <Card className="border-cocoa-100">
                            <CardHeader>
                                <CardTitle className="text-lg text-cocoa-800">Process Instructions</CardTitle>
                            </CardHeader>
                            <CardContent>
                                <div className="whitespace-pre-wrap font-mono text-sm text-slate-600 bg-slate-50 p-4 rounded-lg border border-slate-100 h-full">
                                    {generatedRecipe.instructions}
                                </div>
                            </CardContent>
                        </Card>
                    </div>
                </div>
            )}
        </div>
    );
};

export default CreateRecipe;
